<?xml version='1.0'?>
<package format='3'>
  <name>hpp_romeo</name>
  <version>8.0.0</version>
  <description>Python and ros launch files for Romeo robot in hpp</description>
  <author>Florent Lamiraux</author>
  <maintainer email='guilhem.saurel@laas.fr'>Guilhem Saurel</maintainer>
  <license>BSD-2-Clause</license>

  <depend>example_robot_data</depend>

  <buildtool_depend>cmake</buildtool_depend>
  <build_depend>jrl_cmakemodules</build_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
